backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Summary, name: summary, widget: text, required: false }
      - { label: Cover Image, name: coverImage, widget: image, required: false }
      - { 
          label: Body, 
          name: body, 
          widget: markdown,
          buttons: [
            "bold",
            "italic",
            "code",
            "link",
            "heading-one",
            "heading-two", 
            "heading-three",
            "quote",
            "bulleted-list",
            "numbered-list"
          ]
        }
      - label: Inline Images
        name: inlineImages
        widget: list
        required: false
        fields:
          - { label: Image URL, name: url, widget: string, hint: "Paste Imgur or other image URL here" }
          - { label: Caption, name: caption, widget: string, required: false, hint: "Optional caption for the image" }
          - { label: Alt Text, name: alt, widget: string, required: false, hint: "Description for accessibility" }
  - name: portfolio
    label: Portfolio
    folder: src/content/portfolio
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Video URL, name: videoURL, widget: string }
      - { label: Tags, name: tags, widget: select, multiple: true, options: [Editing, "Motion Graphics", VFX, Color, "Sound Design"] }
      - { label: Description, name: description, widget: text }
      - { label: Thumbnail, name: thumbnail, widget: image }
  - name: pages
    label: Pages
    files:
      - file: src/content/pages/about.md
        label: About
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Headshot, name: headshot, widget: image }
  - name: "home"
    label: "Home"
    folder: "src/content/home"
    create: false
    slug: "index"
    extension: "json"
    editor: { preview: false }
    fields:
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Subline", name: "subline", widget: "text", required: false }
      - { label: "CTA: Portfolio Label", name: "ctaPortfolioLabel", widget: "string", default: "See the spells in action" }
      - { label: "CTA: Portfolio Href", name: "ctaPortfolioHref", widget: "string", default: "/portfolio" }
      - { label: "CTA: Contact Label", name: "ctaContactLabel", widget: "string", default: "Summon me" }
      - { label: "CTA: Contact Href", name: "ctaContactHref", widget: "string", default: "/contact" }
  - name: "skills"
    label: "Skills"
    folder: "src/content/skills"
    create: true
    slug: "{{slug}}"
    extension: "json"
    editor: { preview: false }
    fields:
      - { label: "Name", name: "name", widget: "select", options: ["Editing","Motion Graphics","Visual Effects","Color","Sound Design","3D","AI","Visualizers"] }
      - { label: "POV", name: "pov", widget: "text" }
      - label: "Highlights"
        name: "highlights"
        widget: "list"
        fields: [{ label: "Item", name: "item", widget: "string" }]

  - name: "about"
    label: "About"
    folder: "src/content/about"
    create: false
    slug: "index"
    extension: "json"
    editor: { preview: false }
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Headshot", name: "headshot", widget: "image", required: false }
      - { label: "Additional Content", name: "additionalContent", widget: "markdown", required: false }

