backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }
  - name: portfolio
    label: Portfolio
    folder: src/content/portfolio
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Video URL, name: videoURL, widget: string }
      - { label: Tags, name: tags, widget: select, multiple: true, options: [Editing, "Motion Graphics", VFX, Color, "Sound Design"] }
      - { label: Description, name: description, widget: text }
      - { label: Thumbnail, name: thumbnail, widget: image }
  - name: pages
    label: Pages
    files:
      - file: src/content/pages/about.md
        label: About
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Headshot, name: headshot, widget: image }
 - name: "home"
  label: "Home"
  delete: false
  editor:
    preview: false
  files:
    - name: "homepage"
      label: "Homepage Content"
      file: "src/content/home/home.json"   # ← updated path
      fields:
        - { label: "Headline", name: "headline", widget: "string" }
        - { label: "Subline", name: "subline", widget: "string", required: false }
        - { label: "Intro", name: "intro", widget: "markdown", required: false }
        - { label: "Primary CTA Label", name: "ctaPrimaryLabel", widget: "string", required: false }
        - { label: "Primary CTA URL", name: "ctaPrimaryUrl", widget: "string", required: false }
        - { label: "Secondary CTA Label", name: "ctaSecondaryLabel", widget: "string", required: false }
        - { label: "Secondary CTA URL", name: "ctaSecondaryUrl", widget: "string", required: false }
        - { label: "Hero Image", name: "heroImage", widget: "image", required: false }

