backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }
  - name: portfolio
    label: Portfolio
    folder: src/content/portfolio
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Video URL, name: videoURL, widget: string }
      - { label: Tags, name: tags, widget: select, multiple: true, options: [Editing, "Motion Graphics", VFX, Color, "Sound Design"] }
      - { label: Description, name: description, widget: text }
      - { label: Thumbnail, name: thumbnail, widget: image }
  - name: pages
    label: Pages
    files:
      - file: src/content/pages/about.md
        label: About
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Headshot, name: headshot, widget: image }
  - name: "home"
    label: "Home"
    folder: "src/content/home"
    create: false
    slug: "index"
    extension: "json"
    editor: { preview: false }
    fields:
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Subline", name: "subline", widget: "text", required: false }
      - { label: "CTA: Portfolio Label", name: "ctaPortfolioLabel", widget: "string", default: "See the spells in action" }
      - { label: "CTA: Portfolio Href", name: "ctaPortfolioHref", widget: "string", default: "/portfolio" }
      - { label: "CTA: Contact Label", name: "ctaContactLabel", widget: "string", default: "Summon me" }
      - { label: "CTA: Contact Href", name: "ctaContactHref", widget: "string", default: "/contact" }
  - name: "skills"
    label: "Skills"
    folder: "src/content/skills"
    create: true
    slug: "{{slug}}"
    extension: "json"
    editor: { preview: false }
    fields:
      - { label: "Name", name: "name", widget: "select", options: ["Editing","Motion Graphics","Visual Effects","Color","Sound Design","3D","AI","Visualizers"] }
      - { label: "POV", name: "pov", widget: "text" }
      - label: "Highlights"
        name: "highlights"
        widget: "list"
        fields: [{ label: "Item", name: "item", widget: "string" }]

