backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }
  - name: portfolio
    label: Portfolio
    folder: src/content/portfolio
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Video URL, name: videoURL, widget: string }
      - { label: Tags, name: tags, widget: select, multiple: true, options: [Editing, "Motion Graphics", VFX, Color, "Sound Design"] }
      - { label: Description, name: description, widget: text }
      - { label: Thumbnail, name: thumbnail, widget: image }
  - name: pages
    label: Pages
    files:
      - file: src/content/pages/about.md
        label: About
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
          - { label: Headshot, name: headshot, widget: image }
